e-hal/epiphany-hal.c: Fix missing return statements
Fixes:

   CC       e-hal/src/libe_hal_la-epiphany-hal.lo
 ../e-hal/src/epiphany-hal.c: In function 'e_halt_group':
 ../e-hal/src/epiphany-hal.c:1342:1: error: no return statement in function returning non-void [-Werror=return-type]
  }
  ^
 ../e-hal/src/epiphany-hal.c: In function 'populate_platform_native':
 ../e-hal/src/epiphany-hal.c:1875:1: error: control reaches end of non-void function [-Werror=return-type]
  }
  ^

/
	* e-hal/src/epiphany-hal.c (e_halt_group): Change return type to
	void.
	(populate_platform_native): Return E_OK.

Signed-off-by: Pedro Alves <pedro@palves.net>