e-xml: fread and warn-unused-result
Fixes:

 ../e-xml/src/xml.cpp: In static member function 'static Z<char>* XML::ReadToZ(const char*, XMLTransform*, XMLTransformData*)':
 ../e-xml/src/xml.cpp:5036:43: error: ignoring return value of 'size_t fread(void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
	fread((*y).operator char *(),1,S,fp);
					    ^
 ../e-xml/src/xml.cpp:5043:41: error: ignoring return value of 'size_t fread(void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
	fread(yy.operator char *(),1,S,fp);
					  ^

/
	* e-xml/src/xml.cpp (XML::ReadToZ): Assert fread's expected return.

Signed-off-by: Pedro Alves <pedro@palves.net>