e-utils/e-reset.c: Remove unused local
Fixes:

 ../e-utils/src/e-reset.c:39:31: error: unused variable ‘imask’ [-Werror=unused-variable]
   unsigned cid, cfg, stat, pc, imask;
				^

/
	* e-utils/src/e-reset.c (main): Remove unused 'imask' local.

Signed-off-by: Pedro Alves <pedro@palves.net>