e-lib/e-trace.c: Avoid invalid type-punning
Fixes:

 ../../e-lib/src/e_trace.c: In function ‘trace_write’:
 ../../e-lib/src/e_trace.c:140:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   *traceBufWrPtr++ = *(unsigned long long *)dta;
   ^

/
	* e-lib/src/e_trace.c: Include <string.h>.
	(trace_write): Use memcpy instead of dereferencing type-punned
	pointer.

Signed-off-by: Pedro Alves <pedro@palves.net>