e-server/TargetControlHardware.cpp: Remove unused variables
Fixes:

 ../e-server/src/TargetControlHardware.cpp: In member function ‘int TargetControlHardware::initPlatform(unsigned int)’:
 ../e-server/src/TargetControlHardware.cpp:915:7: error: unused variable ‘err’ [-Werror=unused-variable]
    int err = 0;
	^
 ../e-server/src/TargetControlHardware.cpp: In member function ‘size_t TargetControlHardware::writeTo(unsigned int, void*, size_t)’:
 ../e-server/src/TargetControlHardware.cpp:967:12: error: unused variable ‘coreid’ [-Werror=unused-variable]
    uint32_t coreid, offset, row, col;
	     ^
 ../e-server/src/TargetControlHardware.cpp: In member function ‘size_t TargetControlHardware::readFrom(unsigned int, void*, size_t)’:
 ../e-server/src/TargetControlHardware.cpp:999:12: error: unused variable ‘coreid’ [-Werror=unused-variable]
    uint32_t coreid, offset, row, col;
	     ^

e-server/
	* src/TargetControlHardware.cpp
	(TargetControlHardware::initPlatform): Remove unused 'err' local.
	(TargetControlHardware::writeTo, TargetControlHardware::readFrom):
	Remove unused 'coreid' locals.

Signed-off-by: Pedro Alves <pedro@palves.net>